FROM ${FROM_IMAGE}

# Set image name
ARG IMAGE="${IMAGE}"
ENV ${CONTAINER_IMAGE_ENV_KEY}=$${IMAGE}

# Download service(s) required packages or resources
# RUN ${PACKAGES_INDEX_UPDATE_BIN} \
#     && ${PACKAGES_INSTALL_CLEAN_BIN} \
#        [...]
#     && curl -o resources.tar.gz https://[...].tar.gz
#     && tar -xzf resources.tar.gz

COPY ${DOCKERFILE_SERVICES_DIR} ${CONTAINER_SERVICES_DIR}

# Install and link service(s) to the entrypoint
RUN container-baseimage services install \
    && container-baseimage services link

COPY ${DOCKERFILE_ENVIRONMENT_FILES_DIR} ${CONTAINER_ENVIRONMENT_FILES_DIR}
